### ISSUE TITLE
[Bug]: Article image flickers whilst typing text content

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#1055]
### Describe the bug

When creating an article, the image often flickers as I am typing the content.

### Reproduce

1. Go to create a new article
2. Add an image to it
3. Type in the content input field
4. Observe the image flickering

### Screenshots / Recording

https://github.com/user-attachments/assets/89c94390-294a-49ef-bedf-7ec08a74f9f0

https://github.com/user-attachments/assets/f3ecdd89-4900-4374-b24c-92f375500896

### Web Browser

Version 133.0.6943.55 (Official Build) (arm64)

### Pubky App Version

afd1a3be593d35f31fb1d119aaa2e0a76b918081

### Console log output

```shell

```

**Comment by flaviomoceri** [comment]
Still? I think has been fixed

**Comment by flaviomoceri** [comment]
I will close it, open again if necessary please

**Comment by catch-21** [comment]
Still happening for me on both my Linux machine with Brave browser, and on MacOS with Chrome browser.

**Comment by catch-21** [comment]
Verified in 64bd242d69cba9f34c1e2c231c6b04ece3705e8d
