### ISSUE TITLE
[Bug]: Custom feed replaced when a new one is created using the same tag filter

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#1302]
### Describe the bug

If I already have a custom feed then create a new one, if the tags are the same then the existing one is replaced.

### Reproduce

1. Create a feed with `ai` tag
2. Create a second feed with the same `ai` tag
3. Observe the first feed has been replaced (its tab no longer exists)

### Screenshots / Recording

https://github.com/user-attachments/assets/0a3639e2-e3cb-48b7-ac25-ff8d2ba586bb

### Pubky App Version

e2bb811

### Console log output

```shell

```

**Comment by BitcoinErrorLog** [comment]
Need some logic and error msgs, something like "This feed already exists, overwrite?" maybe

**Comment by flaviomoceri** [comment]
This issue should be fixed, re-open if necessary

**Comment by catch-21** [comment]
Tested in [710cc9b](https://github.com/pubky/pubky-app/tree/710cc9b6c1f5d60330e1a17dd42dc27371a8eb18)
This bug still exists with slightly different behaviour. We do need to prevent creating feeds with identical tags or id them differently to prevent interference.

Two ways to prove issue exists:

**First**
1. Create a feed with any name and single `ai` tag
2. Create a second feed with a different name and single `ai` tag
3. Refresh page
4. Observe the first feed tab no longer exists

**Second**
1. Create a feed with any name and single `ai` tag
2. Create a second feed with a different name and single `ai` tag
3. Edit the name of the most-recently created feed
4. Observe both tabs now share the same name and are treated one and the same (see video below)

https://github.com/user-attachments/assets/f86bf559-9b48-49f7-8529-521708f82169

**Comment by catch-21** [comment]
Verified in 103da8f07419bdf4e08c16afc45058f074c9736a
Now it is not possible to create or edit feeds resulting in either: duplicate name or duplicate filter combination (that's an exact match of: tags, content, filter, view).
