### ISSUE TITLE
[Bug]: Navigating to an profile page that has no posts will show posts of other account

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#530]
### Describe the bug

If a profile that is navigated to has no posts then posts from a previously viewed account will be displayed.

### Reproduce

1. Create a new profile (A) that has no posts
2. Copy this new account's pubky
3. Sign out and sign in as a different account
4. Navigate to an existing profile (B) that has some posts so the posts are listed.
5. Paste the new account's pubky into the search bar and press enter
6. The new account's profile (A) is displayed with the posts from the existing profile (B)

### Screenshots / Recording

<img width="634" alt="Screenshot 2024-10-29 at 15 57 29" src="https://github.com/user-attachments/assets/b1785972-52b9-4c38-b982-efb90af43ad5">

### Web Browser

Version 130.0.6723.59 (Official Build) (arm64)

### Pubky App Version

pubky-nexus v0.1.0

**Comment by flaviomoceri** [comment]
It seems fixed now, in the next release please try again, if so close

**Comment by catch-21** [comment]
Still a problem in 2074afe40666fd912b0a5e86a395525de8a59464

![Screenshot_20241119_142945](https://github.com/user-attachments/assets/3936f0f9-a74b-4215-a8e1-c5271f919fb8)

Errors are:

```
Error: Cannot update a component (`HotReload`) while rendering a different component (`Index`). To locate the bad setState() call inside `Index`, follow the stack trace as described in https://react.dev/link/setstate-in-render
    at createUnhandledError (webpack-internal:///(app-pages-browser)/../../node_modules/next/dist/client/components/react-dev-overlay/internal/helpers/console-error.js:23:19)
    at handleClientError (webpack-internal:///(app-pages-browser)/../../node_modules/next/dist/client/components/react-dev-overlay/internal/helpers/use-error-handler.js:41:56)
    at console.error (webpack-internal:///(app-pages-browser)/../../node_modules/next/dist/client/components/globals/intercept-console-error.js:53:56)
    at scheduleUpdateOnFiber (webpack-internal:///(app-pages-browser)/../../node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:14256:25)
    at dispatchReducerAction (webpack-internal:///(app-pages-browser)/../../node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:7113:14)
    at eval (webpack-internal:///(app-pages-browser)/../../node_modules/next/dist/client/components/react-dev-overlay/app/hot-reloader-client.js:432:9)
    at handleClientError (webpack-internal:///(app-pages-browser)/../../node_modules/next/dist/client/components/react-dev-overlay/internal/helpers/use-error-handler.js:49:9)
    at console.error (webpack-internal:///(app-pages-browser)/../../node_modules/next/dist/client/components/globals/intercept-console-error.js:53:56)
    at Index (webpack-internal:///(app-pages-browser)/./app/profile/components/_Posts.tsx:59:26)
    at react-stack-bottom-frame (webpack-internal:///(app-pages-browser)/../../node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:22341:20)
    at renderWithHooks (webpack-internal:///(app-pages-browser)/../../node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:5732:22)
    at updateFunctionComponent (webpack-internal:///(app-pages-browser)/../../node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:7993:19)
    at beginWork (webpack-internal:///(app-pages-browser)/../../node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:9658:18)
    at runWithFiberInDEV (webpack-internal:///(app-pages-browser)/../../node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:544:16)
    at performUnitOfWork (webpack-internal:///(app-pages-browser)/../../node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:14988:22)
    at workLoopSync (webpack-internal:///(app-pages-browser)/../../node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:14818:41)
    at renderRootSync (webpack-internal:///(app-pages-browser)/../../node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:14796:11)
    at performWorkOnRoot (webpack-internal:///(app-pages-browser)/../../node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:14290:11)
    at performSyncWorkOnRoot (webpack-internal:///(app-pages-browser)/../../node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:15859:7)
    at flushSyncWorkAcrossRoots_impl (webpack-internal:///(app-pages-browser)/../../node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:15721:21)
    at processRootScheduleInMicrotask (webpack-internal:///(app-pages-browser)/../../node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:15755:7)
    at eval (webpack-internal:///(app-pages-browser)/../../node_modules/next/dist/compiled/react-dom/cjs/react-dom-client.development.js:15875:13)
```

and `true` at app/profile/components/_Posts.tsx (51:24) 
`if (isError) console.error(isError);`

**Comment by catch-21** [comment]
Verified in 6385ffbd02634751e6333ba28bffe85881ae0a2f
