### ISSUE TITLE
[Bug]: Tall images are stretched in post input field

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#644]
### Describe the bug

Whilst attaching a tall image to a post, the preview stretches the image to fit.
The image looks fine in the post once published though.

We should scale the image to fit max height so it is not stretched

### Reproduce

1. Drag-drop an image that has a significantly greater height then width into the quick post area
2. Observe the preview of the image

### Screenshots / Recording

![Screenshot_20241119_132043](https://github.com/user-attachments/assets/0bc863fb-54bd-4fe1-9601-7b051d683263)

<img src="https://github.com/user-attachments/assets/be9b4ad2-1c69-4e20-8071-5d1cbee4f807" alt="Alt Text" height="600">

### Web Browser

Version 1.73.89 Chromium: 131.0.6778.69 (Official Build) (64-bit)

### Pubky App Version

2074afe40666fd912b0a5e86a395525de8a59464

**Comment by flaviomoceri** [comment]
If each photo has its own height, then we would have photos of different heights in the preview

**Comment by flaviomoceri** [comment]
maybe you want just to increase max-h?

**Comment by catch-21** [comment]
can't you have a max height (can be same as now) but instead of stretching the width to fill, it scales the width down to keep proportion?

**Comment by MiguelMedeiros** [comment]
fixed: 
![image](https://github.com/user-attachments/assets/930279af-8574-4005-8aab-b40405a429bd)

**Comment by catch-21** [comment]
Tested in 24840dce71c2d092cf624de182fb1a9d7df88258
Not fixed :grin:
![Screenshot_20241204_143039](https://github.com/user-attachments/assets/23dba788-1cad-4916-9fcd-cffa55111811)
