### ISSUE TITLE
[Feature]: Keyboard navigation of search results

### ISSUE THREAD

**Issue by catch-21** [pubky/pubky-beta#815]
### Describe the problem

It is not easy to use the keyboard arrow keys to navigate the list of search results for a couple of reasons:
1. After beginning to type a profile name in the search bar, the up/down arrow keys do nothing. Need to first hover the mouse cursor over one of the results before the up/down arrow keys work.
2. Following on from the first point, when using the up/down arrow keys to select a search result, the search bar doesn't scroll.

### Describe the solution

Make it possible to use the keyboard to type, navigate and select a result without needing the mouse or trackpad.

### Additional context

https://github.com/user-attachments/assets/f6d26636-c1f7-42f4-a1e7-b73428725ea3

**Comment by flaviomoceri** [comment]
This should be fixed, re-open it if necessary

**Comment by catch-21** [comment]
Tested in [710cc9b](https://github.com/pubky/pubky-app/tree/710cc9b6c1f5d60330e1a17dd42dc27371a8eb18)
There has been no change so I'd say this is not fixed. Ideally you can start typing then immediately use keyboard arrow keys to navigate the list. We just need to decide whether we care enough to keep this open.

**Comment by flaviomoceri** [comment]
The second point was already fixed, regarding the first one https://github.com/pubky/pubky-app/pull/1511

**Comment by catch-21** [comment]
Tested on 6c2114c89407e058905e790f8384b0d18a135984
It still doesn't really work for me. It seems to behave the same as `dev` branch. Maybe it's because I am currently on MacOS, where I've noticed the cursor hover position affects scrolling actions differently to other platforms like Ubuntu.

I clicked the search bar, began typing a username, it lists multiple, I use the down arrow key but it navigates my cursor int he search field (because my cursor is still hovering over the search bar). If I move the cursor to the list of users it does kinda work. Maybe that's the best we can get on MacOS. I need to try on non-Mac again...

**Comment by catch-21** [comment]
Verified on bd0c8132d03444be50265f4b3a2dad69a000eeee
Scratch my last comment. This works well.
